spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/RJ
#    username: root
#    password: 1234
#    type: com.alibaba.druid.pool.DruidDataSource  # 设置德鲁伊数据源
  sharding-sphere:
    datasource:
      names:
        master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource  # 设置德鲁伊数据源
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.19.130:3306/rj
        username: root
        password: Miss99..
      slave:
        type: com.alibaba.druid.pool.DruidDataSource  # 设置德鲁伊数据源
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.19.131:3306/rj
        username: root
        password: 1234
    masters-lave: # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      name: dataSource  # 最终数据源名称
      master-data-source-name: master  # 主数据源名称
      slave-data-source-names: slave  # 从数据源名称
    props:
      sql:
        show: true # 开启sql显示 默认false
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB  # ??????????
      max-request-size: 100MB # ?????????? ??????????????
  redis: # redis相关配置
    host: 127.0.0.1 # 本机
    port: 6379
    password:      # 本机无密码
    database: 0    # 工作数据库为0号数据库
  cache:
    redis:
      time-to-live: 180000  # 设置缓存数据过期时间为30分钟
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #控制台输出日志
    map-underscore-to-camel-case: true      # 驼峰命名自动映射

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


RuiJi:
  path: D:\Javacode\RuiJi\src\main\java\com\ztbu\common\food\
