spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/RJ
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource  # 设置德鲁伊数据源
  servlet:
    multipart:
      max-file-size: 10MB  # ??????????
      max-request-size: 100MB # ?????????? ??????????????

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #控制台输出日志
    map-underscore-to-camel-case: true      # 驼峰命名自动映射

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


RuiJi:
  path: D:\Javacode\RuiJi\src\main\java\com\ztbu\common\food\
